### ISSUE TITLE
helix-espagon v1.1.6 causes runtime exception

### ISSUE THREAD

**Issue by stefan-guggisberg** [adobe/helix-resolve-git-ref#161]
**Description**
The latest update from `helix-epsagon v1.1.5` to `v1.1.6` causes the following runtime exception:

```js
Uncaught TypeError [ERR_INVALID_ARG_TYPE]: The "list[0]" argument must be an instance of Buffer or Uint8Array. Received type string ('001e# service=git-upload...)
  at Function.concat (buffer.js:558:13)
  at IncomingMessage.<anonymous> (node_modules/epsagon/dist/bundle.js:1:58912)
  at endReadableNT (_stream_readable.js:1204:12)
```

**To Reproduce**
Run the `resolve-git-ref` action with the following parameters:

```js
{
  "EPSAGON_TOKEN": "<your epsagon token>",
  "owner": "davidnuescheler",
  "repo": "character-landing",
  "ref": "master"
}
```

Note that the error depends on the specific repo being queried. `adobe/helix-home` e.g. works.   

**Expected behavior**
No runtime exception.

**Comment by stefan-guggisberg** [comment]
reverted to epsagon v1.1.5 in 6673c5028

**Comment by tripodsan** [comment]
thanks.
- I reverted the `epsagon-node` of `helix-epsagon` in: https://github.com/adobe/helix-epsagon/commit/55bff851468ee115509a13e5e7ad0643724fb91c
- I created an `espagon-node` issue: https://github.com/epsagon/epsagon-node/issues/243

**Comment by stefan-guggisberg** [comment]
closing this issue as it is resolved by reverting to the previous `helix-epsagon` release. 

The underlying issue is tracked in https://github.com/epsagon/epsagon-node/issues/243
