### ISSUE TITLE
Why "resolve-git-ref" needs to be a service ?

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-resolve-git-ref#298]
I think we use to call `resolve-git-ref` from Fastly but this is not the case anymore. We use then `resolve-git-ref` only in our actions. Each consuming action has to make a call to the service to get the result. This means: 
- make a request to / an activation of the service
- wake up an Adobe I/O Runtime action to make the 2 requests the resolution needs
- wait for the 2 responses
- wait for the service response

The service is called twice for each call to `helix-dispatch` and I am about to introduce a new call with https://github.com/adobe/helix-content-proxy/issues/200. 

The code is pretty simple and solid.

I do not see the value of having `resolve-git-ref` as a service while it could be used as a "standard module" (maybe there is still one): the 2 requests would be sent from within the consuming actions and this would decrease the total number of action invocations and save one request and corresponding activation per utilisation of `resolve-git-ref`.

@stefan-guggisberg @tripodsan @trieloff any thoughts ?

**Comment by trieloff** [comment]
We can turn it into a service/library hybrid (like helix-status) and gradually switch to the library.

**Comment by stefan-guggisberg** [comment]
Good point, I agree. I'll refactor the code, creating a simple zero-dependency node module with the core functionality. The service and other clients will/can use the module/lib directly.

**Comment by stefan-guggisberg** [comment]
0-dependency library: https://github.com/adobe/gh-resolve-ref
