### ISSUE TITLE
Refactor into library and service

### ISSUE THREAD

**Issue by stefan-guggisberg** [adobe/helix-resolve-git-ref#299]
**Is your feature request related to a problem? Please describe.**
See #298. 

**Describe the solution you'd like**
Refactor the core functionality (resolving a git branch/tag to the corresponding commit sha) into a separate minimal (0-dependency) node module. The service will use this module. Other clients can also use this module directly rather than calling the service.

**Additional context**
#298

**Comment by trieloff** [comment]
I'd use this as an opportunity to try the layout suggested here: https://github.com/adobe/helix-resolve-git-ref/pull/295#issuecomment-719871851

I'll then change #299 so that it is non-destructive and can live side-by-side with the library and OW service.

**Comment by stefan-guggisberg** [comment]
> I'd use this as an opportunity to try the layout suggested here: [#295 (comment)](https://github.com/adobe/helix-resolve-git-ref/pull/295#issuecomment-719871851)

that's non trivial and requires more thought. while we could just move the entire root tree to an `ow` subdirectory the CI configuration files would probably need be at the root. And they are likely to be different for different targets (library, ow service, azure service etc).

**Comment by stefan-guggisberg** [comment]
0-dependency library: https://github.com/adobe/gh-resolve-ref

**Comment by stefan-guggisberg** [comment]
fixed in 82f0cd0
