### ISSUE TITLE
Request to unknown repository returns 401

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-resolve-git-ref#5]
**Description**
Trying to resolve a repository that does not exist, resolves in a 401.

**To Reproduce**
```
$ curl -D - 'https://adobeioruntime.net/api/v1/web/helix/helix-services/resolve-git-ref%40v1?org=foo&repo=bar'
HTTP/1.1 401 Unauthorized
...
failed to fetch git repo info (statusCode: 401, statusMessage: Authorization Required)
```

**Expected behavior**
I think that this action should always return a 200, if it was able to perform the lookup action; no matter if it was successful or not. By delegating the github response status to the action response makes it unclear if the action itself needs authentication or just the call to github.

Suggetion:

```
HTTP/1.1 200 OK
{
  "status": "ok",
  "fqRef": "refs/heads/helix-static",
  "sha": "cf5a2060f6de5ad0b7cb24d964974c563f5e7708"
}
```

or 
```
HTTP/1.1 200 OK
{
  "status": "error",
  "statusCode": 401, 
  "statusMessage": "Authorization Required",
}
```

**Comment by stefan-guggisberg** [comment]
`resolve-git-ref` is a [Web Action](https://github.com/apache/incubator-openwhisk/blob/master/docs/webactions.md) and returns  a `{ statusCode, headers, body }` JSON object (see [here](https://github.com/apache/incubator-openwhisk/blob/master/docs/webactions.md#handling-http-requests-with-actions)).  It's unclear to me how an error can be propagated by a Web action other than through `statusCode`. At least I couldn't find a concise spec.

Currently the following errors are handled:
* `404`: the `ref` (tag or branch) is not found
* `400`: missing mandatory parameters (`owner`, `repo`)
* `503`: network related errors, e.g. connection timeout to `github.com`
* `401`: (returned by github) the owner or repo is unknown or the request requires auth to access the information (e.g. for private repos)

**Comment by stefan-guggisberg** [comment]
Regarding the `401` returned for an unknown repo:
Since this is a Web action it doesn't require authorization. But I agree it's ambiguous. I suggest we return a `404` in such a case.

**Comment by tripodsan** [comment]
In https://github.com/adobe/helix-resolve-git-ref/blob/3850b19ad8d6d9d2918cf5fbdd9b357be5312ef0/src/index.js#L46, the response from the lookup request is directly set to the response of the web-action. this is IMO not a good behaviour, as the caller can't distinguish between failures of the web-action or failures of the service that the lookup request is sending.

maybe map all 4xx errors to a: `404 Not Found`.
and all 5xx errors to `502 Bad Gateway`.
